### PR TITLE
Adding Android Builds

### PR DESCRIPTION
**Pull request by Danielku15**
In preparation for having a Skija on Android (https://github.com/JetBrains/skija/issues/101) this PR adds Android builds to the toolchain. This PR includes:

- [x] An Android build matrix to compile Skia with NDK
- [x] Unifying a bit the argument parsing of the python scripts 
- [x] A new input for GitHub Actions to Skip any release related steps (allows better building in forks and trying out things without actually publishing a release)

I couldn't check the binaries yet so I trust that the Skia script handles the compilation well. Next step will be to extend Skija to target Android. 

See latest compilation here: 
https://github.com/Danielku15/skia-build/actions/runs/680600460

### CODE REVIEW

**Comment by nathanieloliveira** [comment]
I can't belive I spent the last day working on basically the same thing 😂. I should have checked the open PRs section.

I'm hoping this gets merged. After implementing this myself, I've arrived at essentially the same implementation as you. My only doubt is: I can't point out when you download or install the Android NDK... 
Should we have a way to specify which version of the NDK to use?
Thanks

**Comment by Danielku15** [comment]
@nathanieloliveira NDK comes pre-shipped with the linux images of GitHub Actions: https://github.com/actions/virtual-environments/blob/ubuntu16/20210318.0/images/linux/Ubuntu1604-README.md

Currently by default it is pointing to 21.4.7075529. GitHub had some issues with the rollout of r22 in GitHub Actions. 
https://github.com/actions/virtual-environments/issues/2420

**Comment by nathanieloliveira** [comment]
> @nathanieloliveira NDK comes pre-shipped with the linux images of GitHub Actions: https://github.com/actions/virtual-environments/blob/ubuntu16/20210318.0/images/linux/Ubuntu1604-README.md
> 
> Currently by default it is pointing to 21.4.7075529. GitHub had some issues with the rollout of r22 in GitHub Actions.
> [actions/virtual-environments#2420](https://github.com/actions/virtual-environments/issues/2420)

Interesting... In my attempt, I was downloading NDK-r22 from google repos and using ubuntu latest image.

**Comment by tonsky** [comment]
Thank you! I’ll take a look soon

**Comment by tonsky** [comment]
Seems to work! https://github.com/JetBrains/skia-build/actions/runs/690480166. Merged as efb641ac5574b2c7d55dd84511deb53e9ed4cc7a. Thank you!

**Pull request closed without merging**
