### PR TITLE
m88-64fc64c948 Add Skottie module & headers

### PR DESCRIPTION
**Pull request by mzgreen**

### CODE REVIEW

**Comment by mzgreen** [comment]
Hey @tonsky! Is there anything wrong with this PR? Should I change anything to get it merged?

**Comment by tonsky** [comment]
Sorry, I am busy fixing SVG linking on Linux. Turned out things are not as simple as I thought they are. Will merge yours next soon

**Comment by mzgreen** [comment]
I see. No rush, I was worried that something is wrong with the PR. Take your time :)

**Comment by tonsky** [comment]
Merged, thank you!

**Pull request closed without merging**
